import {
  createKartfluencer,
  getKartfluencer,
  listKartfluencers,
  updateKartfluencer,
  deleteKartfluencer,
  updateKartfluencerStatus,
  markVisitedByQR,
  addKartfluencerReel,
  listKartfluencerReels,
  updateKartfluencerReel,
  deleteKartfluencerReel,
  updateReelViews,
  approveMilestonePayout,
  getWalletBalance,
  getWalletHistory,
  requestWithdrawal,
  listWithdrawals,
  processWithdrawal,
  rejectWithdrawal,
  createKartfluencerNotification,
  listKartfluencerNotifications,
  toggleKartfluencerNotification,
  deleteKartfluencerNotification,
  importKartfluencerBatch,
  getKartfluencerStats,
  uploadPaymentScreenshot,
  fetchLiveFollowerCount,
  getInfluencerBookingHistory,
  getInfluencerProfileData,
  computeInfluencerScore,
  normalizeReelUrl,
  checkHandleExists,
  verifyInstagramHandle,
  createKartfluencerPublic,
  getKartfluencerPublic,
  listReelsPublic,
  addReelPublic,
  getWalletBalancePublic,
  getWalletHistoryPublic,
  listNotificationsPublic,
  requestWithdrawalPublic,
  KARTFLUENCER_TIERS,
  VIEW_PAYMENT_TIERS,
  getTierForFollowers,
  getTierFromRange,
  getViewTierForCount,
  getViewTierPayout,
  calculateIncrementalPayout,
  type CreateKartfluencerPayload,
  type ListKartfluencersFilter,
  type UpdateKartfluencerPayload,
  type ImportKartfluencerRow,
} from "./kartfluencer-firestore";

export const kartfluencerApi = {
  // Influencers
  create: createKartfluencer,
  get: getKartfluencer,
  list: listKartfluencers,
  update: updateKartfluencer,
  delete: deleteKartfluencer,
  updateStatus: updateKartfluencerStatus,
  // QR Visit
  markVisitedByQR,
  // Reels
  addReel: addKartfluencerReel,
  listReels: listKartfluencerReels,
  updateReel: updateKartfluencerReel,
  deleteReel: deleteKartfluencerReel,
  updateReelViews,
  approveMilestonePayout,
  // Wallet
  getWalletBalance,
  getWalletHistory,
  // Withdrawals
  requestWithdrawal,
  listWithdrawals,
  processWithdrawal,
  rejectWithdrawal,
  // Notifications
  createNotification: createKartfluencerNotification,
  listNotifications: listKartfluencerNotifications,
  toggleNotification: toggleKartfluencerNotification,
  deleteNotification: deleteKartfluencerNotification,
  // Import
  importBatch: importKartfluencerBatch,
  // Stats
  getStats: getKartfluencerStats,
  // Payment
  uploadScreenshot: uploadPaymentScreenshot,
  // Profile
  fetchLiveFollowerCount,
  getInfluencerBookingHistory,
  getInfluencerProfileData,
  computeInfluencerScore,
  // Public Portal (no auth)
  createPublic: createKartfluencerPublic,
  checkHandle: checkHandleExists,
  verifyInstagram: verifyInstagramHandle,
  getPublic: getKartfluencerPublic,
  listReelsPublic,
  addReelPublic,
  getWalletBalancePublic,
  getWalletHistoryPublic,
  listNotificationsPublic,
  requestWithdrawalPublic,
  // Utilities
  normalizeReelUrl,
  tiers: KARTFLUENCER_TIERS,
  viewTiers: VIEW_PAYMENT_TIERS,
  getTierForFollowers,
  getTierFromRange,
  getViewTierForCount,
  getViewTierPayout,
  calculateIncrementalPayout,
};

export type { CreateKartfluencerPayload, ListKartfluencersFilter, UpdateKartfluencerPayload, ImportKartfluencerRow };
